---
title: "Music Insights"
author: "Benjamin Lubetkin"
output: html_notebook
---

First, we need tidyverse to handle data importing and wrangling...

```{r}
install.packages("tidyverse")
library("tidyverse")

survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")
rows <- nrow(survey)
columns <- colnames(survey)
```
Now let us rename the titles in survey:
```{r}
colnames(survey)[colnames(survey) == "Timestamp"] <- "time_submitted"
colnames(survey)[colnames(survey) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"
colnames(survey)[colnames(survey) == "What is your pseudonym?"] <- "pseudonym"
colnames(survey)[colnames(survey) == "Sex"] <- "sex"
colnames(survey)[colnames(survey) == "Major"] <- "academic_major"
colnames(survey)[colnames(survey) == "Academic Year"] <- "academic_level"
colnames(survey)[colnames(survey) == "Year you were born (YYYY)"] <- "year_born"
colnames(survey)[colnames(survey) == "Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"
colnames(survey)[colnames(survey) == "Artist"] <- "favorite_song_artist"
colnames(survey)[colnames(survey) == "Song"] <- "favorite_song"
colnames(survey)[colnames(survey) == "Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"

library("dplyer")
library("tidyr")
```
Let's create a person and a favorite song table:
```{r}
Favorite <- tibble(pseudonym = survey$pseudonym, time_submitted = survey$time_submitted, favorite_song_artist = survey$favorite_song_artist, favorite_song = survey$favorite_song, favorite_song_link = survey$favorite_song_link)

```